# Generated by Django 6.0.7 on 2026-07-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_add_token_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
