# Generated by Django 6.0.7 on 2026-08-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_visit_timing'),
        ('catalog', '0008_doctorclinic_order_by_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='catalog.clinic'),
        ),
    ]
