# Generated by Django 6.0.7 on 2026-08-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('voice', 'Voice')], max_length=16)),
                ('file', models.FileField(upload_to='visit_attachments/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sent_via_whatsapp', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='appointments.appointment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
