# Generated by Django 5.2.12 on 2026-09-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_visitattachment_follow_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_amount_expected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash_at_clinic', 'Cash at Clinic')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_ocr_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_ocr_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='skipped', max_length=16),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('not_required', 'Not Required')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
