# Generated by Django 6.0.7 on 2026-08-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_clinic_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='catalog.clinic'),
        ),
        migrations.CreateModel(
            name='DoctorClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_clinics', to='catalog.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_clinics', to='catalog.doctorprofile')),
            ],
            options={
                'verbose_name': 'doctor clinic',
                'verbose_name_plural': 'doctor clinics',
                'ordering': ['-is_primary', 'clinic__name', 'id'],
                'unique_together': {('doctor', 'clinic')},
            },
        ),
    ]
