# Generated by Django 6.0.7 on 2026-08-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_doctor_clinic_and_availability_clinic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorclinic',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'doctor clinic', 'verbose_name_plural': 'doctor clinics'},
        ),
    ]
