# Generated by Django 5.2.12 on 2026-09-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_doctoravailability_specific_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected consultation fee (PKR) for WhatsApp bank-transfer bookings.', max_digits=10),
        ),
        migrations.CreateModel(
            name='DoctorBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=120)),
                ('account_title', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=64)),
                ('iban', models.CharField(blank=True, default='', max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='catalog.doctorprofile')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at', '-id'],
            },
        ),
    ]
