# Generated by Django 6.0.7 on 2026-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('awaiting_name', 'Awaiting Name'), ('awaiting_otp', 'Awaiting OTP'), ('menu', 'Menu')], default='idle', max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
