# Generated by Django 6.0.7 on 2026-07-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_add_booking_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsession',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('awaiting_name', 'Awaiting Name'), ('awaiting_otp', 'Awaiting OTP'), ('awaiting_speciality', 'Awaiting Speciality'), ('awaiting_doctor', 'Awaiting Doctor'), ('awaiting_confirm', 'Awaiting Confirm'), ('menu', 'Menu')], default='idle', max_length=32),
        ),
    ]
