# Generated by Django 5.2.12 on 2026-09-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_doctorclinic_order_by_created'),
        ('whatsapp', '0004_add_awaiting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsession',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('awaiting_name', 'Awaiting Name'), ('awaiting_otp', 'Awaiting OTP'), ('awaiting_speciality', 'Awaiting Speciality'), ('awaiting_doctor', 'Awaiting Doctor'), ('awaiting_clinic', 'Awaiting Clinic'), ('awaiting_date', 'Awaiting Date'), ('awaiting_slot', 'Awaiting Slot'), ('awaiting_confirm', 'Awaiting Confirm'), ('menu', 'Menu')], default='idle', max_length=32),
        ),
        migrations.CreateModel(
            name='DoctorWhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(blank=True, default='', max_length=64)),
                ('phone_number_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('display_phone', models.CharField(blank=True, default='', max_length=32)),
                ('access_token_encrypted', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='pending', max_length=20)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_account', to='catalog.doctorprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('phone_number_id', ''), _negated=True), fields=('phone_number_id',), name='uniq_wa_phone_number_id_when_set')],
            },
        ),
    ]
