# Generated by Django 5.2.12 on 2026-09-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_payment_ocr_phase1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsession',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('awaiting_name', 'Awaiting Name'), ('awaiting_otp', 'Awaiting OTP'), ('awaiting_booking_mode', 'Awaiting Booking Mode'), ('awaiting_speciality', 'Awaiting Speciality'), ('awaiting_doctor', 'Awaiting Doctor'), ('awaiting_clinic', 'Awaiting Clinic'), ('awaiting_clinic_doctor', 'Awaiting Clinic Doctor'), ('awaiting_date', 'Awaiting Date'), ('awaiting_slot', 'Awaiting Slot'), ('awaiting_confirm', 'Awaiting Confirm'), ('awaiting_payment_method', 'Awaiting Payment Method'), ('awaiting_payment_slip', 'Awaiting Payment Slip'), ('awaiting_faq_question', 'Awaiting FAQ Question'), ('menu', 'Menu')], default='idle', max_length=40),
        ),
    ]
