# Generated by Django 5.2.17 on 2026-10-05 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0010_payment_ocr_phase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('max_bot_replies_per_patient_month', models.PositiveSmallIntegerField()),
                ('max_text_messages_per_day', models.PositiveIntegerField()),
                ('max_voice_notes_per_day', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_bot_replies_per_patient_month__gt', 0)), name='assistant_plan_patient_replies_gt_0'), models.CheckConstraint(condition=models.Q(('max_text_messages_per_day__gt', 0)), name='assistant_plan_text_day_gt_0'), models.CheckConstraint(condition=models.Q(('max_voice_notes_per_day__gte', 0)), name='assistant_plan_voice_day_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='ClinicAssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('system_prompt_extra', models.TextField(blank=True, default='')),
                ('webhook_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('wa_status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], db_index=True, default='pending', max_length=16)),
                ('waba_id', models.CharField(blank=True, default='', max_length=64)),
                ('phone_number_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('display_phone', models.CharField(blank=True, default='', max_length=32)),
                ('meta_app_id', models.CharField(blank=True, default='', max_length=64)),
                ('access_token_encrypted', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('meta_app_secret_encrypted', models.TextField(blank=True, default='')),
                ('verify_token_encrypted', models.TextField(blank=True, default='')),
                ('wa_connected_at', models.DateTimeField(blank=True, null=True)),
                ('wa_last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_config', to='catalog.clinic')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_configs', to='assistant.assistantplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('phone_number_id', ''), _negated=True), fields=('phone_number_id',), name='uniq_assistant_phone_number_id_when_set'), models.CheckConstraint(condition=models.Q(models.Q(('wa_status', 'connected'), _negated=True), models.Q(models.Q(('phone_number_id', ''), _negated=True), models.Q(('access_token_encrypted', ''), _negated=True)), _connector='OR'), name='assistant_connected_requires_phone_and_token')],
            },
        ),
    ]
