# Generated by Django 6.0.7 on 2026-07-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
